### ISSUE TITLE
--partialrun strange behaviour?

### ISSUE THREAD

**Issue by Satome** [isbg/isbg#38] opened 2015-09-28 12:02 UTC
When using the command --partialrun (lets say 100), is it meant to check the first 100 emails, or the last. I noticed when testing this on my work email, which has around 4000 messages stored, it only reads the first 100 oldest messages (with uid 1,2,3 ect).
Also when running with the --partialrun multiple times, it ignores the messages already seen and starts going further on the message list (from 1 to 100, 101 to 200). I did get around this by modifying the uid check so, that it first gets the uids, then limits the amount of uids we want to handle and then checks if we have already gone through them.

**Comment by baldurmen** [comment] 2015-10-23 20:43
Sorry for not responding to this earlier, I'm REALLY busy so I don't have _any_ time to work on ISBG.

The --partialrun option was kinda hacked on the fly recently but is not satisfactory IMHO.

The problem is that isbg isn't currently written as a main() (I'm working on this..). Once this will be done, isbg will run in sequences of X messages by default with a nice loop.

Since this function will be rewritten, this is not a priority... If you wish to submit a patch I'll find time to review and pull (promised).

**Comment by Satome** [comment] 2015-10-23 21:48
No worries, take your time. It works well enough for now :). I'll send the
patch next week if I have the time

**Comment by baldurmen** [comment] 2018-07-01 18:34
fixed in the latest version. `partialrun` should now behave properly.

**Closed by baldurmen** 2018-07-01 18:34 UTC
Labels: bug
